version: '3'

services:
  jupyter:
    image: 'jupyter/datascience-notebook:latest'
    ports: 
      - '10000:8888'
    volumes:
      - jupyter_datascientist:/home/jovyan/work
    container_name: jupyter
    environment:
      JUPYTER_ENABLE_LAB: 'yes'

volumes:
  jupyter_datascientist: